export const copy = {
  promptUser: 'guest@drnhfr',
  promptUserRoot: 'root@drnhfr',
  motd: [
    'drnhfr-sh 1.0 (x86_64-unknown-linux-gnu)',
    '',
    ' * Documentation:  type "help" or "?"',
    ' * Getting around: type "ls", then "cd"',
    '',
    'Last login: never, from a machine much like this one.',
  ],
  reloading: 'reloading …',
  restarting: 'restarting …',
  whoami:
    'christian dirnhofer. builds distributed systems for a living, actors and circuit boards for fun.',
  emptyLs: '(empty)',
  cmdNotFoundSuffix: 'command not found',
  helpHeading: 'available commands:',
  catMissing: 'cat: missing operand',
  catNotFoundPrefix: 'cat: no such file: ',
  catNoDescription: 'no description available.',
  cdNotFoundPrefix: 'cd: no such directory: ',
  suMissing: 'su: please supply the root password',
  suWrong: 'su: authentication failure. nice try.',
  suSuccess: 'access granted. you are root.',
  suHintPrefix: 'the cv is mounted and listed in the nav — or: cd ',
  cvDescription: 'the cv. root only.',
  exitDone: 'back to guest. cv locked.',
  exitIdle: 'already guest.',
  chips: [
    { label: 'ls', run: 'ls' },
    { label: 'neofetch', run: 'neofetch' },
    { label: 'help', run: 'help' },
  ],
} as const;
